# Generated by Django 5.1.7 on 2025-04-27 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("real_name", models.CharField(max_length=100)),
                ("birthdate", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("F", "여자"), ("M", "남자")], max_length=1
                    ),
                ),
                (
                    "cold_sensitivity",
                    models.CharField(
                        choices=[("민감", "민감"), ("보통", "보통"), ("둔감", "둔감")],
                        max_length=10,
                    ),
                ),
                (
                    "heat_sensitivity",
                    models.CharField(
                        choices=[("민감", "민감"), ("보통", "보통"), ("둔감", "둔감")],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
