# Generated by Django 5.1.7 on 2025-04-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="comment_images/"),
        ),
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
