# Generated by Django 5.1.7 on 2025-04-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0004_comment_image_comment_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
